var countries = ["afghanistan",
"albania",
"algeria",
"andorra",
"angola",
"antigua and barbuda",
"argentina",
"armenia",
"australia",
"austria",
"azerbaijan",
"bahamas",
"bahrain",
"bangladesh",
"barbados",
"belarus",
"belgium",
"belize",
"benin",
"bhutan",
"bolivia",
"bosnia and herzegovina",
"botswana",
"brazil",
"brunei",
"bulgaria",
"burkina faso",
"burundi",
"cambodia",
"cameroon",
"canada",
"cape verde",
"central african republic",
"chad",
"chile",
"china",
"colombia",
"comoros",
"congo",
"congo",
"costa rica",
"cote d'ivoire",
"croatia",
"cuba",
"cyprus",
"czech republic",
"denmark",
"djibouti",
"dominica",
"dominican republic",
"ecuador",
"egypt",
"el salvador",
"equatorial guinea",
"eritrea",
"estonia",
"ethiopia",
"fiji",
"finland",
"france",
"gabon",
"gambia",
"georgia",
"germany",
"ghana",
"greece",
"grenada",
"guatemala",
"guinea",
"guinea-bissau",
"guyana",
"haiti",
"honduras",
"hungary",
"iceland",
"india",
"indonesia",
"iran",
"iraq",
"ireland",
"israel",
"italy",
"jamaica",
"japan",
"jordan",
"kazakhstan",
"kenya",
"kiribati",
"korea",
"korea",
"kuwait",
"kyrgyzstan",
"laos",
"latvia",
"lebanon",
"lesotho",
"liberia",
"libya",
"liechtenstein",
"lithuania",
"luxembourg",
"macedonia",
"madagascar",
"malawi",
"malaysia",
"maldives",
"mali",
"malta",
"marshall islands",
"mauritania",
"mauritius",
"mexico",
"micronesia",
"moldova",
"monaco",
"mongolia",
"montenegro",
"morocco",
"mozambique",
"myanmar",
"namibia",
"nauru",
"nepal",
"netherlands",
"new zealand",
"nicaragua",
"niger",
"nigeria",
"norway",
"oman",
"pakistan",
"palau",
"panama",
"papua new guinea",
"paraguay",
"peru",
"philippines",
"poland",
"portugal",
"qatar",
"romania",
"russia",
"rwanda",
"saint kitts and nevis",
"saint lucia",
"saint vincent and the grenadines",
"samoa",
"san marino",
"sao tome and principe",
"saudi arabia",
"senegal",
"serbia",
"seychelles",
"sierra leone",
"singapore",
"slovakia",
"slovenia",
"solomon islands",
"somalia",
"south africa",
"spain",
"sri lanka",
"sudan",
"suriname",
"swaziland",
"sweden",
"switzerland",
"syria",
"tajikistan",
"tanzania",
"thailand",
"timor-leste",
"togo",
"tonga",
"trinidad and tobago",
"tunisia",
"turkey",
"turkmenistan",
"tuvalu",
"uganda",
"ukraine",
"united arab emirates",
"united kingdom",
"united states",
"uruguay",
"uzbekistan",
"vanuatu",
"vatican city",
"venezuela",
"vietnam",
"yemen",
"zambia",
"zimbabwe",
"abkhazia",
"china",
"nagorno-karabakh",
"northern cyprus",
"pridnestrovie",
"somaliland",
"south ossetia",
"ashmore and cartier islands",
"christmas island",
"cocos",
"coral sea islands",
"heard island and mcdonald islands",
"norfolk island",
"new caledonia",
"french polynesia",
"mayotte",
"saint barthelemy",
"saint martin",
"saint pierre and miquelon",
"wallis and futuna",
"french southern and antarctic lands",
"clipperton island",
"bouvet island",
"cook islands",
"niue",
"tokelau",
"guernsey",
"isle of man",
"jersey",
"anguilla",
"bermuda",
"british indian ocean territory",
"british sovereign base areas",
"british virgin islands",
"cayman islands",
"falkland islands",
"gibraltar",
"montserrat",
"pitcairn islands",
"saint helena",
"south georgia & south sandwich islands",
"turks and caicos islands",
"northern mariana islands",
"puerto rico",
"american samoa",
"baker island",
"guam",
"howland island",
"jarvis island",
"johnston atoll",
"kingman reef",
"midway islands",
"navassa island",
"palmyra atoll",
"u.s. virgin islands",
"wake island",
"hong kong",
"macau",
"faroe islands",
"greenland",
"french guiana",
"guadeloupe",
"martinique",
"reunion",
"aland",
"aruba",
"netherlands antilles",
"svalbard",
"ascension",
"tristan da cunha",
"australian antarctic territory",
"ross dependency",
"peter i island",
"queen maud land",
"british antarctic territory",
"usa"]